name: flutter_searchable_treeview2
version: 2.0.0
description: >
  A widget, that visualises a tree structure, where a node can be any widget.
repository: https://github.com/wenkaifan0720/flutter_searchable_treeview

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
